### ISSUE TITLE
"powered by owncloud" icons?

### ISSUE THREAD

**Issue by Vdragon** [owncloud/promo#1]
Hi, 
I'm wondering if there's an official set "powered by owncloud" icons?

**Comment by jancborchardt** [comment]
@Vdragon no there isn’t. You could use the simple text »Powered by ownCloud« and link to [ownCloud.org](https://owncloud.org) or also use the logos / sticker graphic from this repository.

What do you want to use it for?

**Comment by Vdragon** [comment]
@jancborchardt 
> What do you want to use it for?
Just a little attribution on our experimental service's `index.html`.  Thanks for answering!

**Comment by jancborchardt** [comment]
@Vdragon cool, thank you! :) So best just use the logo itself.
